name: Setup C++ toolchain

runs:
  using: "composite"

  steps:
    - shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          clang \
          cmake \
          lcov \
          libopenblas-dev \
          liblapack-dev \
          llvm
