import numpy as np

class ComplexMixer:
    """
    Complex frequency-shifting mixer implemented using a CORDIC-style iterative rotator
    and a numerically controlled oscillator (NCO).

    This class performs high-precision complex mixing without relying on direct
    trigonometric evaluations. It precomputes a set of complex rotation factors
    based on the number of CORDIC iterations and uses them to iteratively rotate
    incoming I/Q samples. The mixer supports arbitrary input lengths and produces
    a real-valued mixed output.

    Parameters
    ----------
    n_iter : int, optional
        Number of CORDIC iterations used to refine the rotation accuracy.
        Higher values improve precision but increase computation time.
    f_res : float, optional
        Frequency resolution used to determine the internal NCO word length.

    Notes
    -----
    The mixer computes a maximum phase accumulator size based on the sampling
    frequency and the desired frequency resolution. A numerically controlled
    oscillator (NCO) generates phase increments, and the CORDIC loop applies
    iterative rotations to each complex input sample.
    """

    def __init__(self, n_iter: int = 13, f_res: float = 1.0) -> None:
        """
        Initialize the ComplexMixer.

        Parameters
        ----------
        n_iter : int, optional
            Number of CORDIC iterations. Controls the precision of the rotation.
        f_res : float, optional
            Frequency resolution used to determine the NCO word length.

        """
        self.__f_res = f_res
        self.__factors = 1 + 1j * 2 ** np.linspace(1, -(n_iter - 1), n_iter + 1)
        self.__factors[0] = 1j

    def __call__(self, f_shift: float, fs: float, I_in: np.ndarray, Q_in: np.ndarray) -> np.ndarray:
        """
        Apply complex mixing to I/Q input samples.

        Generates a complex exponential at frequency `f_shift` using an NCO,
        then applies iterative CORDIC rotations to mix the input signal.
        The result is a real-valued waveform representing the frequency-shifted
        signal.

        Parameters
        ----------
        f_shift : float
            Desired frequency shift.
        fs : float
            Sampling frequency. Must be strictly positive.
        I_in : ndarray
            In-phase input samples.
        Q_in : ndarray
            Quadrature input samples.

        Returns
        -------
        ndarray
            Real-valued mixed output samples.

        Raises
        ------
        ValueError
            If `fs <= 0`.
        """
        if fs <= 0:
            raise ValueError("ComplexMixer.__call__: Sampling frequency must be positive.")

        L = int(np.ceil(np.log2(fs / self.__f_res)))
        W_max = 2 ** L

        W = np.fmod(f_shift * W_max / fs, W_max)
        Z = self.__NCO(W, W_max, len(I_in))

        I_out = self.__CORDIC(W_max, Z, I_in, Q_in)
        return I_out

    def __CORDIC(self, W_max: int, Z: np.ndarray, I_in: np.ndarray, Q_in: np.ndarray) -> np.ndarray:
        """
        Perform CORDIC vector rotations on I/Q samples.

        Iteratively rotates each complex input sample using precomputed
        rotation factors. The rotation direction is determined by the
        instantaneous phase error stored in the NCO accumulator.

        Parameters
        ----------
        W_max : int
            Maximum phase accumulator value.
        Z : ndarray
            Phase accumulator values generated by the NCO.
        I_in : ndarray
            In-phase input samples.
        Q_in : ndarray
            Quadrature input samples.

        Returns
        -------
        ndarray
            Real-valued rotated output samples.
        """
        I_out = np.zeros(len(I_in))

        for i, (x, y, z) in enumerate(zip(I_in, Q_in, Z)):
            v = x + 1j * y

            for k, factor in enumerate(self.__factors):
                a = W_max * np.angle(factor) / (2 * np.pi)

                if z > 0 and z < W_max / 2:
                    v *= factor / np.sqrt(1 + 2 ** (-2 * k))
                    rotation = -1
                else:
                    v *= np.conj(factor) / np.sqrt(1 + 2 ** (-2 * k))
                    rotation = 1

                z = np.fmod(z + rotation * a + W_max, W_max)

            I_out[i] = v.real

        return I_out

    def __NCO(self, W: float, W_max: int, n_points: int) -> np.ndarray:
        """
        Generate NCO phase accumulator values.

        Computes accumulated phase increments for the desired frequency shift
        and wraps them into the valid range of the phase accumulator.

        Parameters
        ----------
        W : float
            Phase increment per sample.
        W_max : int
            Maximum phase accumulator value.
        n_points : int
            Number of samples to generate.

        Returns
        -------
        ndarray
            Wrapped phase accumulator values.
        """
        Z = W * np.arange(n_points + 1)
        Z = np.fmod(Z, W_max)
        return Z
